---
# tasks file for deploy-jenkins
- name: Ensure jenkins directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /home/ec2-user/share/jenkins

- name: Pull the latest official jenkins docker image
  docker_image:
    name: "jenkins/jenkins"
    source: pull

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkins-server"
    image: "jenkins/jenkins"
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - "/home/ec2-user/share/jenkins:/var/jenkins_home"
    state: started
    recreate: no

#- name: Copy systemd service script to start and stop the jenkins container
#  copy: src=services/jenkins.service dest=/etc/systemd/system
#
#- name: Reload systemctl
#  shell: systemctl restart jenkins
#
#- name: Enable the docker-jenkins service
#  shell: systemctl enable jenkins